pass args to scripts
pnpm/pn pull request #49
Opened 2023-07-28 18:40 UTC by Yakiyo

Pass any additional arguments passed after script name in command invocation to the script.

Resolves https://github.com/pnpm/pn/issues/48

2023-07-30 17:14 UTC, Yakiyo commented
Any status on this?

2023-08-01 22:49 UTC, zkochan commented on src/main.rs
> +        // not sure creating vec with cap makes much diff here
This comment should be removed

2023-08-02 03:23 UTC, Yakiyo commented on src/main.rs
> +        // not sure creating vec with cap makes much diff here
done

2023-08-02 04:13 UTC, KSXGitHub requested changes

2023-08-02 04:13 UTC, KSXGitHub commented on src/main.rs
> +    };
Is it really necessary to allocate a whole `Vec` just to join a string?

```suggestion
    let command_string = |name: &str, args: &[String]| {
        let mut string = name.to_string();
        for arg in args {
            string += " ";
            string += arg;
        }
        string
    };
```

2023-08-02 04:13 UTC, KSXGitHub commented on src/main.rs
> +                    let commands = command_string(command, args[1..].to_vec());
Why `.to_vec()`?

2023-08-02 14:57 UTC, KSXGitHub commented on src/main.rs
> +                    print_and_run_script(&manifest, &name, &commands, &cwd)
Why plural?

```suggestion
                    let command = command_string(command, args.args);
                    print_and_run_script(&manifest, &name, &command, &cwd)
```

You don't need to be concerned about name collision, Rust will shadow the name.

2023-08-02 14:58 UTC, KSXGitHub commented on src/main.rs
> +                    return print_and_run_script(&manifest, name, &commands, &cwd);
Please remove the plural here also.

2023-08-02 14:59 UTC, KSXGitHub commented on src/main.rs
> +                    return print_and_run_script(&manifest, name, &commands, &cwd);
```suggestion
                    let command = command_string(command, args[1..].to_vec());
                    return print_and_run_script(&manifest, name, &command, &cwd);
```

2023-08-02 15:02 UTC, KSXGitHub requested changes
What about the arguments that contain whitespaces? Don't we need to escape them before passing the command to `sh -c`?

Related crates: https://docs.rs/shell-escape/0.1.5/shell_escape/

2023-08-03 14:52 UTC, Yakiyo commented
> What about the arguments that contain whitespaces? Don't we need to escape them before passing the command to `sh -c`?
> 
> Related crates: https://docs.rs/shell-escape/0.1.5/shell_escape/

Not sure what that would look like. care to give an example? How does pnpm do it?

2023-08-03 15:07 UTC, KSXGitHub commented
> Not sure what that would look like. care to give an example? How does pnpm do it?

pnpm for sure handles whitespace.

![proof](https://github.com/pnpm/pn/assets/11488886/fbe54b8e-2de3-4527-8932-7e3e22e244cf)

But for pnpm did it, you must ask @zkochan.

If you ask me, I have already answered: Just use the crate I suggested, I don't really care how exactly pnpm did it.

2023-08-03 16:09 UTC, Yakiyo commented
> pnpm for sure handles whitespace.
> 

i tried it out a few seconds ago but clap handles it. 
passing `pn run test "Hello World" "! !"` takes it as two args instead of 4.

2023-08-03 16:18 UTC, Yakiyo commented
okay i understand the issue now
![image](https://github.com/pnpm/pn/assets/91675932/f92f651c-c1ee-4fb4-a385-3f2373290e62)

2023-08-03 16:23 UTC, KSXGitHub commented
If you used my [list-args.js](https://user-images.githubusercontent.com/11488886/258154159-fbe54b8e-2de3-4527-8932-7e3e22e244cf.png), the issue would have been clearer.

Also, please use the `shell-quote` crate as suggested [here](https://github.com/pnpm/pn/pull/49#issuecomment-1664169793).

2023-08-04 13:53 UTC, Yakiyo commented
@KSXGitHub not sure if i did anything wrong but it doesnt seem to work

![image](https://github.com/pnpm/pn/assets/91675932/ea8b292d-a205-40be-bf52-5f5c7a2f8ab6)

and based on the ci, shell quote is failing to build on windows.

2023-08-04 13:55 UTC, Yakiyo commented
`env::args_os` itself is stripping away the quotes
![image](https://github.com/pnpm/pn/assets/91675932/0f6e0396-b8af-46fb-a6ef-416abbe35ef6)

2023-08-04 14:19 UTC, KSXGitHub commented
> shell quote is failing to build on windows.

This was an oversight on my part. I was not aware that shell-quote is not cross-platform. Let's try [os_display](https://docs.rs/os_display/0.1.3/os_display/).

Also, changing the type of `RunArgs::args` to `Vec<OsString>` seems to lead to verbose code, let's reverse that.

2023-08-05 15:58 UTC, KSXGitHub requested changes
See https://github.com/Yakiyo/pn/pull/1

2023-08-05 16:02 UTC, Yakiyo commented
> See [Yakiyo#1](https://github.com/Yakiyo/pn/pull/1)

merged

2023-08-05 16:10 UTC, KSXGitHub commented
> Windows CI fails

CLRF strikes again.

2023-08-05 16:12 UTC, KSXGitHub commented on tests/test_main.rs
> +        .stdout(include_str!("fixtures/append-script-args/stdout.txt"));
```suggestion
        .stdout(include_str!("fixtures/append-script-args/stdout.txt").replace("\r\n", "\n"));
```

2023-08-05 16:13 UTC, KSXGitHub approved these changes

2023-08-05 16:38 UTC, KSXGitHub requested changes
Can you merge this? https://github.com/Yakiyo/pn/pull/2

2023-08-05 16:56 UTC, Yakiyo commented
> Can you merge this? [Yakiyo#2](https://github.com/Yakiyo/pn/pull/2)

done

2023-08-05 22:56 UTC, zkochan approved these changes

2023-08-05 22:57 UTC, merged