Use `thiserror` crate to derive `std::error::Error` for error enums
pnpm/pn pull request #67
Opened 2024-11-19 08:08 UTC by Turbo87

This PR uses the popular https://github.com/dtolnay/thiserror crate for deriving `std::error::Error` (and `Display` and optionally `From`) for the error enums `PnError` and `MainError`.

2024-12-06 17:07 UTC, Turbo87 commented
@KSXGitHub any thoughts on this? :)

2024-12-06 17:13 UTC, KSXGitHub requested changes
`derive_more` already has `Error`.

2024-12-06 17:14 UTC, KSXGitHub commented
Initially, we don't derive the `Error` trait because we don't use it. Can you explain why the `Error` trait necessary at all?

2024-12-07 07:44 UTC, Turbo87 commented
> `derive_more` already has `Error`.

ah, indeed, I wasn't aware of that. I was going for `thiserror` because it's the far more popular library, but I guess it's indeed not necessary here.

2024-12-07 07:44 UTC, closed without merging

2024-12-07 10:50 UTC, KSXGitHub commented
I used to use `thiserror` too, but found that it didn't provide anyway to customize the trait bounds, which caused me a real headache, until I found out that `derive_more` (a crate I already use) also provide `Error` macro, and its trait bound can be customized.

Anyway, `pn` is a binary, not a library, so we don't derive traits we don't use. If only there is a way to make the compiler warns us about unused trait impls.